// Parse the target Flutter project (the CWD when users run the tool).
//
// Two pieces of information matter for the cross-build:
//   1. The application-level metadata (`name`, entrypoint, assets).
//   2. The list of plugins that declare Windows support, resolved through
//      the package config produced by `flutter pub get`.
//
// We intentionally do NOT invoke `flutter pub get` ourselves — callers
// should ensure the project is resolved beforehand. `doctor` and `build`
// both check `.dart_tool/package_config.json` freshness.

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'exceptions.dart';

/// A plugin dependency that declares a Windows platform implementation.
class WindowsPluginRef {
  WindowsPluginRef({
    required this.name,
    required this.rootPath,
    required this.pluginClass,
    this.dartPluginClass,
  });

  /// Package name, e.g. `url_launcher_windows`.
  final String name;

  /// Absolute path to the plugin package root (where its `pubspec.yaml`
  /// lives). The Windows CMake project is under `<rootPath>/windows/`.
  final String rootPath;

  /// C++ class registered by the plugin (from pubspec `flutter.plugin`
  /// `platforms.windows.pluginClass`).
  final String pluginClass;

  /// Optional Dart-only plugin class (federated plugins).
  final String? dartPluginClass;

  String get windowsCMakeDir => p.join(rootPath, 'windows');

  bool get hasNativeCode => File(p.join(windowsCMakeDir, 'CMakeLists.txt')).existsSync();
}

class FlutterProject {
  FlutterProject._({
    required this.root,
    required this.appName,
    required this.entryPoint,
    required this.pubspec,
    required this.plugins,
    required this.hasWindowsScaffold,
  });

  /// 仅用于单元测试：允许不读取磁盘直接构造实例。
  // ignore: sort_unnamed_constructors_first
  FlutterProject.forTesting({
    required this.root,
    required this.appName,
    required this.entryPoint,
    required String windowsDir,
    required this.hasWindowsScaffold,
    required this.plugins,
  }) : pubspec = YamlMap();

  final String root;
  final String appName;
  final String entryPoint;
  final YamlMap pubspec;
  final List<WindowsPluginRef> plugins;

  /// Whether the project already contains a `windows/` directory scaffolded
  /// by `flutter create --platforms=windows`. Required for the runner build.
  final bool hasWindowsScaffold;

  String get windowsDir => p.join(root, 'windows');
  String get windowsRunnerDir => p.join(windowsDir, 'runner');
  String get windowsFlutterDir => p.join(windowsDir, 'flutter');

  /// Load the project rooted at [projectRoot] (defaults to CWD).
  static Future<FlutterProject> load({String? projectRoot}) async {
    final root = p.normalize(Directory(projectRoot ?? Directory.current.path).absolute.path);

    final pubspecFile = File(p.join(root, 'pubspec.yaml'));
    if (!pubspecFile.existsSync()) {
      throw ProjectException(
        'No pubspec.yaml at $root — not a Dart/Flutter project.',
      );
    }
    final pubspec = loadYaml(pubspecFile.readAsStringSync());
    if (pubspec is! YamlMap) {
      throw ProjectException('pubspec.yaml did not parse as a YAML map.');
    }
    if (pubspec['flutter'] == null) {
      throw ProjectException(
        'pubspec.yaml has no `flutter:` section — is this a Flutter app?',
      );
    }

    final appName = pubspec['name'] as String? ?? 'app';
    final entryPoint = p.join(root, 'lib', 'main.dart');
    if (!File(entryPoint).existsSync()) {
      throw ProjectException(
        'Application entrypoint not found: $entryPoint',
      );
    }

    final packageConfig = File(p.join(root, '.dart_tool', 'package_config.json'));
    if (!packageConfig.existsSync()) {
      throw ProjectException(
        'Missing .dart_tool/package_config.json.',
        hint: 'Run `flutter pub get` in $root first.',
      );
    }
    final plugins = _resolveWindowsPlugins(root, packageConfig);

    final windowsDir = Directory(p.join(root, 'windows'));
    final hasScaffold = windowsDir.existsSync() &&
        File(p.join(windowsDir.path, 'CMakeLists.txt')).existsSync();

    return FlutterProject._(
      root: root,
      appName: appName,
      entryPoint: entryPoint,
      pubspec: pubspec,
      plugins: plugins,
      hasWindowsScaffold: hasScaffold,
    );
  }

  /// Emit the CMake include file that the runner's `flutter/` folder expects
  /// (`generated_plugins.cmake`), listing each plugin that ships native code.
  ///
  /// Mirrors the file `flutter build windows` generates on Windows.
  String renderGeneratedPluginsCmake() {
    final withCpp = plugins.where((p) => p.hasNativeCode).toList();
    final buf = StringBuffer()
      ..writeln('# Generated by flutter_build. Do not edit.')
      ..writeln('list(APPEND FLUTTER_PLUGIN_LIST');
    for (final plugin in withCpp) {
      buf.writeln('  ${plugin.name}');
    }
    buf
      ..writeln(')')
      ..writeln('')
      ..writeln('list(APPEND FLUTTER_FFI_PLUGIN_LIST')
      ..writeln(')')
      ..writeln('')
      ..writeln('set(PLUGIN_BUNDLED_LIBRARIES)')
      ..writeln('')
      ..writeln('foreach(plugin \${FLUTTER_PLUGIN_LIST})')
      ..writeln('  add_subdirectory(flutter/ephemeral/.plugin_symlinks/\${plugin}/windows plugins/\${plugin})')
      ..writeln('  target_link_libraries(\${BINARY_NAME} PRIVATE \${plugin}_plugin)')
      ..writeln('  list(APPEND PLUGIN_BUNDLED_LIBRARIES \$<TARGET_FILE:\${plugin}_plugin>)')
      ..writeln('  list(APPEND PLUGIN_BUNDLED_LIBRARIES \${\${plugin}_bundled_libraries})')
      ..writeln('endforeach(plugin)');
    return buf.toString();
  }

  /// Emit the C++ side of plugin registration expected under
  /// `windows/flutter/generated_plugin_registrant.{h,cc}`.
  (String header, String source) renderGeneratedPluginRegistrant() {
    final withCpp = plugins.where((p) => p.hasNativeCode).toList();
    final header = StringBuffer()
      ..writeln('//  Generated by flutter_build. Do not edit.')
      ..writeln('#ifndef GENERATED_PLUGIN_REGISTRANT_')
      ..writeln('#define GENERATED_PLUGIN_REGISTRANT_')
      ..writeln('')
      ..writeln('#include <flutter/plugin_registry.h>')
      ..writeln('')
      ..writeln('void RegisterPlugins(flutter::PluginRegistry* registry);')
      ..writeln('')
      ..writeln('#endif  // GENERATED_PLUGIN_REGISTRANT_');

    final src = StringBuffer()
      ..writeln('//  Generated by flutter_build. Do not edit.')
      ..writeln('#include "generated_plugin_registrant.h"')
      ..writeln('');
    for (final pl in withCpp) {
      src.writeln('#include <${pl.name}/${pl.name}_plugin.h>');
    }
    src
      ..writeln('')
      ..writeln('void RegisterPlugins(flutter::PluginRegistry* registry) {');
    for (final pl in withCpp) {
      src.writeln(
        '  ${pl.pluginClass}RegisterWithRegistrar(\n'
        '      registry->GetRegistrarForPlugin("${pl.pluginClass}"));',
      );
    }
    src.writeln('}');
    return (header.toString(), src.toString());
  }

  static List<WindowsPluginRef> _resolveWindowsPlugins(
    String projectRoot,
    File packageConfig,
  ) {
    final Object? decoded;
    try {
      decoded = jsonDecode(packageConfig.readAsStringSync());
    } catch (e) {
      throw ProjectException('Failed to parse package_config.json: $e');
    }
    if (decoded is! Map<String, dynamic>) {
      throw ProjectException('package_config.json has unexpected structure.');
    }
    final packages = decoded['packages'];
    if (packages is! List) {
      return const [];
    }

    final result = <WindowsPluginRef>[];
    for (final entry in packages) {
      if (entry is! Map) continue;
      final name = entry['name'] as String?;
      final rootUri = entry['rootUri'] as String?;
      if (name == null || rootUri == null) continue;

      final Uri absolute;
      final base = Uri.file(p.join(packageConfig.path));
      absolute = base.resolve(rootUri);
      final pkgRoot = p.normalize(absolute.toFilePath());
      final pluginPubspec = File(p.join(pkgRoot, 'pubspec.yaml'));
      if (!pluginPubspec.existsSync()) continue;

      final Object? y;
      try {
        y = loadYaml(pluginPubspec.readAsStringSync());
      } catch (_) {
        continue;
      }
      if (y is! YamlMap) continue;
      final flutter = y['flutter'];
      if (flutter is! YamlMap) continue;
      final plugin = flutter['plugin'];
      if (plugin is! YamlMap) continue;
      final platforms = plugin['platforms'];
      if (platforms is! YamlMap) continue;
      final windows = platforms['windows'];
      if (windows is! YamlMap) continue;

      result.add(WindowsPluginRef(
        name: name,
        rootPath: pkgRoot,
        pluginClass: windows['pluginClass'] as String? ?? '',
        dartPluginClass: windows['dartPluginClass'] as String?,
      ));
    }
    return result;
  }
}
